/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.DespesasDAO;
import DAO.ReceitasDAO;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import minhagrana.Categoria;
import minhagrana.Despesa;

/**
 *
 * @author arthur
 import minhagrana.Receita;
*/
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        atualizarDashboard();

        ListCategorias.setModel(new DefaultListModel<>());
    }

    private void navegarPara(String card) {
        java.awt.CardLayout cl = (java.awt.CardLayout) painelConteudo.getLayout();
        cl.show(painelConteudo, card);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSidebar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        painelConteudo = new javax.swing.JPanel();
        painelDashboard = new javax.swing.JPanel();
        cardSaldo = new javax.swing.JPanel();
        lblSaldoTitulo = new javax.swing.JLabel();
        lblSaldoValor = new javax.swing.JLabel();
        cardReceitas = new javax.swing.JPanel();
        lblReceitasTitulo = new javax.swing.JLabel();
        lblReceitasValor = new javax.swing.JLabel();
        cardDespesas = new javax.swing.JPanel();
        lblDespesasTitulo = new javax.swing.JLabel();
        lblDespesasValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLancamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        painelCategorias = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNovaCategoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListCategorias = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        painelRelatorios = new javax.swing.JPanel();
        cardResumoGeral = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalReceitasValor = new javax.swing.JLabel();
        lblTotalDespesasValor = new javax.swing.JLabel();
        lblTotalSaldorValor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MinhaGrana");
        setSize(new java.awt.Dimension(1000, 650));

        painelSidebar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Receitas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        painelSidebar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelSidebar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jButton3.setText("Despesas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        painelSidebar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, -1));

        jButton5.setText("Categorias");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        painelSidebar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, -1));

        jButton6.setText("Relatórios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        painelSidebar.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, -1));

        painelConteudo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelConteudo.setLayout(new java.awt.CardLayout());

        painelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSaldoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSaldoTitulo.setText("Saldo:");

        lblSaldoValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSaldoValor.setText("R$ 0,00");

        javax.swing.GroupLayout cardSaldoLayout = new javax.swing.GroupLayout(cardSaldo);
        cardSaldo.setLayout(cardSaldoLayout);
        cardSaldoLayout.setHorizontalGroup(
            cardSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSaldoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cardSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardSaldoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSaldoValor))
                    .addComponent(lblSaldoTitulo))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        cardSaldoLayout.setVerticalGroup(
            cardSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaldoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldoValor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painelDashboard.add(cardSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 100));

        cardReceitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblReceitasTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReceitasTitulo.setText("Receitas:");

        lblReceitasValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReceitasValor.setText("R$ 0,00");

        javax.swing.GroupLayout cardReceitasLayout = new javax.swing.GroupLayout(cardReceitas);
        cardReceitas.setLayout(cardReceitasLayout);
        cardReceitasLayout.setHorizontalGroup(
            cardReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReceitasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cardReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardReceitasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblReceitasValor))
                    .addComponent(lblReceitasTitulo))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        cardReceitasLayout.setVerticalGroup(
            cardReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReceitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReceitasTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReceitasValor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painelDashboard.add(cardReceitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 210, 100));

        cardDespesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDespesasTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDespesasTitulo.setText("Despesas:");

        lblDespesasValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDespesasValor.setText("R$ 0,00");

        javax.swing.GroupLayout cardDespesasLayout = new javax.swing.GroupLayout(cardDespesas);
        cardDespesas.setLayout(cardDespesasLayout);
        cardDespesasLayout.setHorizontalGroup(
            cardDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDespesasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cardDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardDespesasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDespesasValor))
                    .addComponent(lblDespesasTitulo))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        cardDespesasLayout.setVerticalGroup(
            cardDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDespesasTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDespesasValor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painelDashboard.add(cardDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 210, 100));

        tabelaLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Descrição", "Tipo", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLancamentos);

        painelDashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 670, 290));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ultimos Lançamentos");
        painelDashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        painelConteudo.add(painelDashboard, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Categoria de Despesas");

        btnNovaCategoria.setText("+ Nova Categoria");
        btnNovaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCategoriaActionPerformed(evt);
            }
        });

        ListCategorias.setToolTipText("");
        jScrollPane2.setViewportView(ListCategorias);

        jLabel3.setText("________________________________________________________________________________");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCategoriasLayout = new javax.swing.GroupLayout(painelCategorias);
        painelCategorias.setLayout(painelCategoriasLayout);
        painelCategoriasLayout.setHorizontalGroup(
            painelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCategoriasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovaCategoria)
                .addGap(25, 25, 25))
            .addGroup(painelCategoriasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(painelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        painelCategoriasLayout.setVerticalGroup(
            painelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCategoriasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(painelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnNovaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(97, 97, 97))
        );

        painelConteudo.add(painelCategorias, "card6");

        cardResumoGeral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Total Receitas:");

        jLabel7.setText("Total Despesas:");

        jLabel8.setText("Total Saldo:");

        lblTotalReceitasValor.setText("R$ 0,00");

        lblTotalDespesasValor.setText("R$ 0,00");

        lblTotalSaldorValor.setText("R$ 0,00");

        javax.swing.GroupLayout cardResumoGeralLayout = new javax.swing.GroupLayout(cardResumoGeral);
        cardResumoGeral.setLayout(cardResumoGeralLayout);
        cardResumoGeralLayout.setHorizontalGroup(
            cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardResumoGeralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardResumoGeralLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalReceitasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardResumoGeralLayout.createSequentialGroup()
                        .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalDespesasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSaldorValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardResumoGeralLayout.setVerticalGroup(
            cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardResumoGeralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalReceitasValor))
                .addGap(21, 21, 21)
                .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDespesasValor)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(cardResumoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSaldorValor)
                    .addComponent(jLabel8))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Resumo Geral");
        jLabel4.setToolTipText("");

        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Categoria/Origem", "Tipo", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRelatorio);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Relatório");

        jLabel9.setText("_______________________________________________________________________________");

        btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGerarRelatorio.setText("+ Gerar");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRelatoriosLayout = new javax.swing.GroupLayout(painelRelatorios);
        painelRelatorios.setLayout(painelRelatoriosLayout);
        painelRelatoriosLayout.setHorizontalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRelatoriosLayout.createSequentialGroup()
                .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGerarRelatorio))
                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                        .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelRelatoriosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(420, 420, 420))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelRelatoriosLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardResumoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(19, 19, 19))
        );
        painelRelatoriosLayout.setVerticalGroup(
            painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRelatoriosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(btnGerarRelatorio))
                .addGap(18, 18, 18)
                .addGroup(painelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cardResumoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(painelRelatoriosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        painelConteudo.add(painelRelatorios, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        telas.DialogReceita dialog = new telas.DialogReceita(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        atualizarDashboard();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        navegarPara("card2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        telas.DialogDespesa dialog = new telas.DialogDespesa(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        atualizarDashboard();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        navegarPara("card6");
        carregarCategorias();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        navegarPara("card7");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnNovaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCategoriaActionPerformed
        String nome = javax.swing.JOptionPane.showInputDialog(this, "Nome da nova categoria:");
        if (nome != null && !nome.trim().isEmpty()) {
            DAO.CategoriaDAO dao = new DAO.CategoriaDAO();
            dao.inserir(new minhagrana.Categoria(nome.trim()));
            carregarCategorias();
            
        }
    }//GEN-LAST:event_btnNovaCategoriaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int selecionado = ListCategorias.getSelectedIndex();
        
        if (selecionado == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria para excluir", "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }
        int confirmar = JOptionPane.showConfirmDialog(this, "Deseja excluir essa categoria?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (confirmar == JOptionPane.YES_OPTION) {
            DAO.CategoriaDAO dao = new DAO.CategoriaDAO();
            List<minhagrana.Categoria> lista = dao.listarTodas();
            minhagrana.Categoria categoria = lista.get(selecionado);
            dao.excluir(categoria.getId());
            carregarCategorias();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        
        DAO.ReceitasDAO receitasDAO = new ReceitasDAO();
        DAO.DespesasDAO despesasDAO = new DespesasDAO();
        
        List<minhagrana.Receita> receitas = receitasDAO.listarTodas();
        List<minhagrana.Despesa> despesas = despesasDAO.listarTodos();
        
        double totalReceitas = 0;
        for (minhagrana.Receita r : receitas) {
            totalReceitas += r.getValor();
        }
        
        double totalDespesas = 0;
        for (minhagrana.Despesa d : despesas) {
            totalDespesas += d.getValor();
        }
            
       double saldo = totalReceitas - totalDespesas;

        // preecher os lbl do card resumo
        lblTotalReceitasValor.setText(String.format("R$ %.2f", totalReceitas));
        lblTotalDespesasValor.setText(String.format("R$ %.2f", totalDespesas));
        lblTotalSaldorValor.setText(String.format("R$ %.2f", saldo));
        
        DefaultTableModel model = (DefaultTableModel) tblRelatorio.getModel();
        model.setRowCount(0);
        
        
        for (minhagrana.Receita r : receitas) {
            model.addRow(new Object[]{
                r.getData(),
                r.getOrigem(),
                "Receita",
                String.format("R$ %.2f", r.getValor())
            });

        }
        
        for (minhagrana.Despesa d : despesas) {
            model.addRow(new Object[]{
                d.getData(),
                d.getCategoria().getNome(),
                "Despesa",
                String.format("R$ %.2f", d.getValor())
            });
        
            }
        
        
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListCategorias;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnNovaCategoria;
    private javax.swing.JPanel cardDespesas;
    private javax.swing.JPanel cardReceitas;
    private javax.swing.JPanel cardResumoGeral;
    private javax.swing.JPanel cardSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDespesasTitulo;
    private javax.swing.JLabel lblDespesasValor;
    private javax.swing.JLabel lblReceitasTitulo;
    private javax.swing.JLabel lblReceitasValor;
    private javax.swing.JLabel lblSaldoTitulo;
    private javax.swing.JLabel lblSaldoValor;
    private javax.swing.JLabel lblTotalDespesasValor;
    private javax.swing.JLabel lblTotalReceitasValor;
    private javax.swing.JLabel lblTotalSaldorValor;
    private javax.swing.JPanel painelCategorias;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelDashboard;
    private javax.swing.JPanel painelRelatorios;
    private javax.swing.JPanel painelSidebar;
    private javax.swing.JTable tabelaLancamentos;
    private javax.swing.JTable tblRelatorio;
    // End of variables declaration//GEN-END:variables

    public void atualizarDashboard() {
        DAO.ReceitasDAO receitasDAO = new ReceitasDAO();
        DAO.DespesasDAO despesasDAO = new DespesasDAO();
        
        List<minhagrana.Receita> receitas = receitasDAO.listarTodas();
        List<minhagrana.Despesa> despesas = despesasDAO.listarTodos();
        
        double totalReceitas = 0;
        for (minhagrana.Receita r : receitas) {
            totalReceitas += r.getValor();
        }
        
        double totalDespesas = 0;
        for (minhagrana.Despesa d : despesas) {
            totalDespesas += d.getValor();
        }
            
       double saldo = totalReceitas - totalDespesas;
        
        lblSaldoValor.setText(String.format("R$ %.2f", saldo));
        lblReceitasValor.setText(String.format("R$ %.2f", totalReceitas));
        lblDespesasValor.setText(String.format("R$ %.2f", totalDespesas));

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tabelaLancamentos.getModel();
        model.setRowCount(0);

        
        for (minhagrana.Receita r : receitas) {
            model.addRow(new Object[]{
                r.getData(),
                r.getDescricao(),
                "Receita",
                String.format("R$ %.2f", r.getValor())
            });

        }
        
        for (minhagrana.Despesa d : despesas) {
            model.addRow(new Object[]{
                d.getData(),
                d.getDescricao(),
                "Despesa",
                String.format("R$ %.2f", d.getValor())
            });
        }
        
    }

    private void carregarCategorias() {
        DefaultListModel<String> model = new DefaultListModel<>();
        DAO.CategoriaDAO dao = new DAO.CategoriaDAO();
        for (Categoria c : dao.listarTodas()) {
            model.addElement(c.getNome());
        }

        ListCategorias.setModel(model);
    }

}
